apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: blink-runner
    app.kubernetes.io/managed-by: Kustomize
    app.kubernetes.io/name: blink-runner
    app.kubernetes.io/version: 1.0.763
  name: blink-runner
spec:
  template:
    spec:
      containers:
        - name: blink-runner
          image: "blinkops/blink-runner:1.0.763"
