apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blink-runner
bases:
- ../../base
patchesStrategicMerge:
- secret.yaml
- configmap.yaml
- deployment.yaml
patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: blink
  patch: |-
    - op: replace
      path: /metadata/name
      value: blink-runner