apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - role.yaml
  - role-binding.yaml
  - secret.yaml
  - serviceaccount.yaml