apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: blink-namespace-admin
rules:
  - apiGroups: [ "","apps" ] # "" indicates the core API group
    resources: [ "configmaps", "deployments", "deployments/scale", "pods", "services" ]
    verbs: [ "create", "delete", "describe", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "*" ]
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "create", "delete", "describe", "get", "list", "patch", "update", "watch" ]
