apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blink-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: blink-namespace-admin
subjects:
  - kind: ServiceAccount
    name: blink-runner