apiVersion: v1
kind: ConfigMap
metadata:
  name: blink-runner-config
  labels:
    name: config
data:
  config.yml: |-
        logger:
          log_format: text
          log_level: info
          log_output: stdout
        nats:
          nats_url: ws://blink-controller:8080/gw/
        runner:
          action_timeout: 60
          ctrl_url: https://trr-app.blinkops.com
          retry_count: 5
          retry_duration: 5
        vault:
          vault_url: http://vault.vault.svc.cluster.local:8200

